Resources:
  NicknamesTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      AttributeDefinitions:
        - AttributeName: slug
          AttributeType: S
      KeySchema:
        - AttributeName: slug
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      TableName: ${self:custom.legacyTableName}
  MainTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      AttributeDefinitions:
        - AttributeName: key
          AttributeType: S
        - AttributeName: sort
          AttributeType: S
        - AttributeName: data
          AttributeType: S
      KeySchema:
        - AttributeName: key
          KeyType: HASH
        - AttributeName: sort
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      TableName: ${self:custom.tableName}
      GlobalSecondaryIndexes:
        - IndexName: ${self:custom.gsi1}
          Projection:
            ProjectionType: ALL
          KeySchema:
            - AttributeName: sort
              KeyType: HASH
            - AttributeName: data
              KeyType: RANGE
